package com.atguigu.mapper;

import com.atguigu.bean.AddressCopy1;

public interface AddressCopy1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(AddressCopy1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(AddressCopy1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    AddressCopy1 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(AddressCopy1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(AddressCopy1 record);
}