package com.atguigu.mapper;

import com.atguigu.bean.BankCase;
import com.atguigu.bean.BankCaseWithBLOBs;

public interface BankCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_case
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(Long casId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_case
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(BankCaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_case
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(BankCaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_case
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    BankCaseWithBLOBs selectByPrimaryKey(Long casId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_case
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(BankCaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_case
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(BankCaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_case
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(BankCase record);
}