package com.atguigu.mapper;

import com.atguigu.bean.CallRecord;

public interface CallRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(CallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(CallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    CallRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(CallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(CallRecord record);
}