package com.atguigu.mapper;

import com.atguigu.bean.CallRecordCopy;

public interface CallRecordCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(CallRecordCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(CallRecordCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    CallRecordCopy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(CallRecordCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CallRecordCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(CallRecordCopy record);
}