package com.atguigu.mapper;

import com.atguigu.bean.CasePaid1;

public interface CasePaid1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(CasePaid1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(CasePaid1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    CasePaid1 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(CasePaid1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CasePaid1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(CasePaid1 record);
}