package com.atguigu.mapper;

import com.atguigu.bean.CaseApplyCopy1;
import com.atguigu.bean.CaseApplyCopy1WithBLOBs;

public interface CaseApplyCopy1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(CaseApplyCopy1WithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(CaseApplyCopy1WithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    CaseApplyCopy1WithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(CaseApplyCopy1WithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CaseApplyCopy1WithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_apply_copy1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(CaseApplyCopy1 record);
}