package com.atguigu.mapper;

import com.atguigu.bean.CaseCarLoan;

public interface CaseCarLoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(CaseCarLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(CaseCarLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    CaseCarLoan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(CaseCarLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_car_loan
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(CaseCarLoan record);
}