package com.atguigu.mapper;

import com.atguigu.bean.CasePerson;

public interface CasePersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_person
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_person
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(CasePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_person
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(CasePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_person
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    CasePerson selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_person
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(CasePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_person
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(CasePerson record);
}