package com.atguigu.mapper;

import com.atguigu.bean.CusCity;

public interface CusCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(Long cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(CusCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(CusCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    CusCity selectByPrimaryKey(Long cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(CusCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_city
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(CusCity record);
}