package com.atguigu.mapper;

import com.atguigu.bean.EntrustLinkman;

public interface EntrustLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_linkman
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_linkman
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(EntrustLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_linkman
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(EntrustLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_linkman
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    EntrustLinkman selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_linkman
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(EntrustLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_linkman
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(EntrustLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_linkman
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(EntrustLinkman record);
}