package com.atguigu.mapper;

import com.atguigu.bean.LastPhoneTime;

public interface LastPhoneTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table last_phone_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(String caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table last_phone_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(LastPhoneTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table last_phone_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(LastPhoneTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table last_phone_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    LastPhoneTime selectByPrimaryKey(String caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table last_phone_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(LastPhoneTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table last_phone_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(LastPhoneTime record);
}