package com.atguigu.mapper;

import com.atguigu.bean.LimUser;

public interface LimUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lim_user
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(String userCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lim_user
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(LimUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lim_user
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(LimUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lim_user
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    LimUser selectByPrimaryKey(String userCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lim_user
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(LimUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lim_user
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LimUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lim_user
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(LimUser record);
}