package com.atguigu.mapper;

import com.atguigu.bean.PhoneRecord;

public interface PhoneRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(PhoneRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(PhoneRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    PhoneRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(PhoneRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(PhoneRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(PhoneRecord record);
}