package com.atguigu.mapper;

import com.atguigu.bean.SalEmp;
import com.atguigu.bean.SalEmpWithBLOBs;

public interface SalEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_emp
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(Long seNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_emp
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(SalEmpWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_emp
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(SalEmpWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_emp
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    SalEmpWithBLOBs selectByPrimaryKey(Long seNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_emp
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(SalEmpWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_emp
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SalEmpWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_emp
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(SalEmp record);
}