package com.atguigu.mapper;

import com.atguigu.bean.Sheet0;

public interface Sheet0Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet0
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(Sheet0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet0
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(Sheet0 record);
}