package com.atguigu.mapper;

import com.atguigu.bean.Ss;

public interface SsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(Ss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(Ss record);
}