package com.atguigu.mapper;

import com.atguigu.bean.SysColumnCopy;

public interface SysColumnCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(SysColumnCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(SysColumnCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    SysColumnCopy selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(SysColumnCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column_copy
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(SysColumnCopy record);
}