package com.atguigu.mapper;

import java.util.List;
import java.util.Map;

import com.atguigu.bean.SysOrganization;

public interface SysOrganizationMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_organization
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_organization
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	int insert(SysOrganization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_organization
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	int insertSelective(SysOrganization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_organization
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	SysOrganization selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_organization
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	int updateByPrimaryKeySelective(SysOrganization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_organization
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	int updateByPrimaryKey(SysOrganization record);

	List<SysOrganization> selectAll();

	List<Integer> select_parentId();

	List<SysOrganization> selectChildren(Map<String, Object> map);

}