package com.atguigu.mapper;

import java.util.List;

import com.atguigu.bean.SysPosition;

public interface SysPositionMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_position
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_position
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	int insert(SysPosition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_position
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	int insertSelective(SysPosition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_position
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	SysPosition selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_position
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	int updateByPrimaryKeySelective(SysPosition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_position
	 *
	 * @mbggenerated Sat Apr 21 11:25:08 CST 2018
	 */
	int updateByPrimaryKey(SysPosition record);

	List<SysPosition> selectChildren(int id);

	List<SysPosition> selectAll();
}