package com.atguigu.mapper;

import com.atguigu.bean.SysUserResourceRelationKey;

public interface SysUserResourceRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_resource_relation
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(SysUserResourceRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_resource_relation
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(SysUserResourceRelationKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_resource_relation
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(SysUserResourceRelationKey record);
}