package com.atguigu.mapper;

import com.atguigu.bean.Table2;

public interface Table2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(Table2 record);
}