package com.atguigu.mapper;

import com.atguigu.bean.TBasePinyin;

public interface TBasePinyinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_pinyin
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_pinyin
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(TBasePinyin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_pinyin
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(TBasePinyin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_pinyin
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    TBasePinyin selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_pinyin
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(TBasePinyin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_pinyin
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(TBasePinyin record);
}