package com.atguigu.mapper;

import com.atguigu.bean.TimelenOutStatistics;

public interface TimelenOutStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timelen_out_statistics
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timelen_out_statistics
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insert(TimelenOutStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timelen_out_statistics
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int insertSelective(TimelenOutStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timelen_out_statistics
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    TimelenOutStatistics selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timelen_out_statistics
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKeySelective(TimelenOutStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timelen_out_statistics
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    int updateByPrimaryKey(TimelenOutStatistics record);
}