package com.atguigu.bean;

public class BankCaseWithBLOBs extends BankCase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_tremark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casTremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_warn
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casWarn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_pre_rec
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casPreRec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_remark2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casRemark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_remark3
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casRemark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_remark4
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casRemark4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_remark5
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casRemark5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_hom_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casHomAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_work_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casWorkAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_mail_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casMailAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_reg_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casRegAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_con_add1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casConAdd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_con_add2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casConAdd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_remark6
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casRemark6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_note
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_con_add3
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casConAdd3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_con_add4
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casConAdd4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_remark7
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casRemark7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_remark8
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casRemark8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_con_u_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casConUAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_con_add_5
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casConAdd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_assign_ids
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casAssignIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_assign_names
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casAssignNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.cas_assign_times
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String casAssignTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_case.his_remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String hisRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_tremark
     *
     * @return the value of bank_case.cas_tremark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasTremark() {
        return casTremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_tremark
     *
     * @param casTremark the value for bank_case.cas_tremark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasTremark(String casTremark) {
        this.casTremark = casTremark == null ? null : casTremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_warn
     *
     * @return the value of bank_case.cas_warn
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasWarn() {
        return casWarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_warn
     *
     * @param casWarn the value for bank_case.cas_warn
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasWarn(String casWarn) {
        this.casWarn = casWarn == null ? null : casWarn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_pre_rec
     *
     * @return the value of bank_case.cas_pre_rec
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasPreRec() {
        return casPreRec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_pre_rec
     *
     * @param casPreRec the value for bank_case.cas_pre_rec
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasPreRec(String casPreRec) {
        this.casPreRec = casPreRec == null ? null : casPreRec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_remark
     *
     * @return the value of bank_case.cas_remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasRemark() {
        return casRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_remark
     *
     * @param casRemark the value for bank_case.cas_remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasRemark(String casRemark) {
        this.casRemark = casRemark == null ? null : casRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_remark2
     *
     * @return the value of bank_case.cas_remark2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasRemark2() {
        return casRemark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_remark2
     *
     * @param casRemark2 the value for bank_case.cas_remark2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasRemark2(String casRemark2) {
        this.casRemark2 = casRemark2 == null ? null : casRemark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_remark3
     *
     * @return the value of bank_case.cas_remark3
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasRemark3() {
        return casRemark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_remark3
     *
     * @param casRemark3 the value for bank_case.cas_remark3
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasRemark3(String casRemark3) {
        this.casRemark3 = casRemark3 == null ? null : casRemark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_remark4
     *
     * @return the value of bank_case.cas_remark4
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasRemark4() {
        return casRemark4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_remark4
     *
     * @param casRemark4 the value for bank_case.cas_remark4
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasRemark4(String casRemark4) {
        this.casRemark4 = casRemark4 == null ? null : casRemark4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_remark5
     *
     * @return the value of bank_case.cas_remark5
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasRemark5() {
        return casRemark5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_remark5
     *
     * @param casRemark5 the value for bank_case.cas_remark5
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasRemark5(String casRemark5) {
        this.casRemark5 = casRemark5 == null ? null : casRemark5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_hom_add
     *
     * @return the value of bank_case.cas_hom_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasHomAdd() {
        return casHomAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_hom_add
     *
     * @param casHomAdd the value for bank_case.cas_hom_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasHomAdd(String casHomAdd) {
        this.casHomAdd = casHomAdd == null ? null : casHomAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_work_add
     *
     * @return the value of bank_case.cas_work_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasWorkAdd() {
        return casWorkAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_work_add
     *
     * @param casWorkAdd the value for bank_case.cas_work_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasWorkAdd(String casWorkAdd) {
        this.casWorkAdd = casWorkAdd == null ? null : casWorkAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_mail_add
     *
     * @return the value of bank_case.cas_mail_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasMailAdd() {
        return casMailAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_mail_add
     *
     * @param casMailAdd the value for bank_case.cas_mail_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasMailAdd(String casMailAdd) {
        this.casMailAdd = casMailAdd == null ? null : casMailAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_reg_add
     *
     * @return the value of bank_case.cas_reg_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasRegAdd() {
        return casRegAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_reg_add
     *
     * @param casRegAdd the value for bank_case.cas_reg_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasRegAdd(String casRegAdd) {
        this.casRegAdd = casRegAdd == null ? null : casRegAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_con_add1
     *
     * @return the value of bank_case.cas_con_add1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasConAdd1() {
        return casConAdd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_con_add1
     *
     * @param casConAdd1 the value for bank_case.cas_con_add1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasConAdd1(String casConAdd1) {
        this.casConAdd1 = casConAdd1 == null ? null : casConAdd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_con_add2
     *
     * @return the value of bank_case.cas_con_add2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasConAdd2() {
        return casConAdd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_con_add2
     *
     * @param casConAdd2 the value for bank_case.cas_con_add2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasConAdd2(String casConAdd2) {
        this.casConAdd2 = casConAdd2 == null ? null : casConAdd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_remark6
     *
     * @return the value of bank_case.cas_remark6
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasRemark6() {
        return casRemark6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_remark6
     *
     * @param casRemark6 the value for bank_case.cas_remark6
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasRemark6(String casRemark6) {
        this.casRemark6 = casRemark6 == null ? null : casRemark6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_note
     *
     * @return the value of bank_case.cas_note
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasNote() {
        return casNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_note
     *
     * @param casNote the value for bank_case.cas_note
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasNote(String casNote) {
        this.casNote = casNote == null ? null : casNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_con_add3
     *
     * @return the value of bank_case.cas_con_add3
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasConAdd3() {
        return casConAdd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_con_add3
     *
     * @param casConAdd3 the value for bank_case.cas_con_add3
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasConAdd3(String casConAdd3) {
        this.casConAdd3 = casConAdd3 == null ? null : casConAdd3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_con_add4
     *
     * @return the value of bank_case.cas_con_add4
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasConAdd4() {
        return casConAdd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_con_add4
     *
     * @param casConAdd4 the value for bank_case.cas_con_add4
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasConAdd4(String casConAdd4) {
        this.casConAdd4 = casConAdd4 == null ? null : casConAdd4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_remark7
     *
     * @return the value of bank_case.cas_remark7
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasRemark7() {
        return casRemark7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_remark7
     *
     * @param casRemark7 the value for bank_case.cas_remark7
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasRemark7(String casRemark7) {
        this.casRemark7 = casRemark7 == null ? null : casRemark7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_remark8
     *
     * @return the value of bank_case.cas_remark8
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasRemark8() {
        return casRemark8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_remark8
     *
     * @param casRemark8 the value for bank_case.cas_remark8
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasRemark8(String casRemark8) {
        this.casRemark8 = casRemark8 == null ? null : casRemark8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_con_u_add
     *
     * @return the value of bank_case.cas_con_u_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasConUAdd() {
        return casConUAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_con_u_add
     *
     * @param casConUAdd the value for bank_case.cas_con_u_add
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasConUAdd(String casConUAdd) {
        this.casConUAdd = casConUAdd == null ? null : casConUAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_con_add_5
     *
     * @return the value of bank_case.cas_con_add_5
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasConAdd5() {
        return casConAdd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_con_add_5
     *
     * @param casConAdd5 the value for bank_case.cas_con_add_5
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasConAdd5(String casConAdd5) {
        this.casConAdd5 = casConAdd5 == null ? null : casConAdd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_assign_ids
     *
     * @return the value of bank_case.cas_assign_ids
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasAssignIds() {
        return casAssignIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_assign_ids
     *
     * @param casAssignIds the value for bank_case.cas_assign_ids
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasAssignIds(String casAssignIds) {
        this.casAssignIds = casAssignIds == null ? null : casAssignIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_assign_names
     *
     * @return the value of bank_case.cas_assign_names
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasAssignNames() {
        return casAssignNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_assign_names
     *
     * @param casAssignNames the value for bank_case.cas_assign_names
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasAssignNames(String casAssignNames) {
        this.casAssignNames = casAssignNames == null ? null : casAssignNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.cas_assign_times
     *
     * @return the value of bank_case.cas_assign_times
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCasAssignTimes() {
        return casAssignTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.cas_assign_times
     *
     * @param casAssignTimes the value for bank_case.cas_assign_times
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCasAssignTimes(String casAssignTimes) {
        this.casAssignTimes = casAssignTimes == null ? null : casAssignTimes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_case.his_remark
     *
     * @return the value of bank_case.his_remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getHisRemark() {
        return hisRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_case.his_remark
     *
     * @param hisRemark the value for bank_case.his_remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setHisRemark(String hisRemark) {
        this.hisRemark = hisRemark == null ? null : hisRemark.trim();
    }
}