package com.atguigu.bean;

public class CaseApplyCopy1WithBLOBs extends CaseApplyCopy1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply_copy1.apply_content
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String applyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply_copy1.hurry_content
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String hurryContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_apply_copy1.remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply_copy1.apply_content
     *
     * @return the value of case_apply_copy1.apply_content
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getApplyContent() {
        return applyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply_copy1.apply_content
     *
     * @param applyContent the value for case_apply_copy1.apply_content
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setApplyContent(String applyContent) {
        this.applyContent = applyContent == null ? null : applyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply_copy1.hurry_content
     *
     * @return the value of case_apply_copy1.hurry_content
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getHurryContent() {
        return hurryContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply_copy1.hurry_content
     *
     * @param hurryContent the value for case_apply_copy1.hurry_content
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setHurryContent(String hurryContent) {
        this.hurryContent = hurryContent == null ? null : hurryContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_apply_copy1.remark
     *
     * @return the value of case_apply_copy1.remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_apply_copy1.remark
     *
     * @param remark the value for case_apply_copy1.remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}