package com.atguigu.bean;

public class CaseTestWithBLOBs extends CaseTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_test.old_collec_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String oldCollecRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_test.remark1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_test.remark2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String remark2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_test.old_collec_record
     *
     * @return the value of case_test.old_collec_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getOldCollecRecord() {
        return oldCollecRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_test.old_collec_record
     *
     * @param oldCollecRecord the value for case_test.old_collec_record
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setOldCollecRecord(String oldCollecRecord) {
        this.oldCollecRecord = oldCollecRecord == null ? null : oldCollecRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_test.remark1
     *
     * @return the value of case_test.remark1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_test.remark1
     *
     * @param remark1 the value for case_test.remark1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_test.remark2
     *
     * @return the value of case_test.remark2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_test.remark2
     *
     * @param remark2 the value for case_test.remark2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }
}