package com.atguigu.bean;

public class EntrustVisitWithBLOBs extends EntrustVisit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_visit.negotiation_target
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String negotiationTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_visit.negotiation_schedule
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String negotiationSchedule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_visit.negotiation_target
     *
     * @return the value of entrust_visit.negotiation_target
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getNegotiationTarget() {
        return negotiationTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_visit.negotiation_target
     *
     * @param negotiationTarget the value for entrust_visit.negotiation_target
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setNegotiationTarget(String negotiationTarget) {
        this.negotiationTarget = negotiationTarget == null ? null : negotiationTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_visit.negotiation_schedule
     *
     * @return the value of entrust_visit.negotiation_schedule
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getNegotiationSchedule() {
        return negotiationSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_visit.negotiation_schedule
     *
     * @param negotiationSchedule the value for entrust_visit.negotiation_schedule
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setNegotiationSchedule(String negotiationSchedule) {
        this.negotiationSchedule = negotiationSchedule == null ? null : negotiationSchedule.trim();
    }
}