package com.atguigu.bean;

import java.util.Date;

public class SocialSecurity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.case_apply_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String caseApplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.unit_name
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.unit_phone1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String unitPhone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.unit_address
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String unitAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.unit_phone2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String unitPhone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.linkman
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.phone
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.last_renew_date
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private Date lastRenewDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.create_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.create_emp_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security.remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.id
     *
     * @return the value of social_security.id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.id
     *
     * @param id the value for social_security.id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.case_apply_id
     *
     * @return the value of social_security.case_apply_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCaseApplyId() {
        return caseApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.case_apply_id
     *
     * @param caseApplyId the value for social_security.case_apply_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCaseApplyId(String caseApplyId) {
        this.caseApplyId = caseApplyId == null ? null : caseApplyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.unit_name
     *
     * @return the value of social_security.unit_name
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.unit_name
     *
     * @param unitName the value for social_security.unit_name
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.unit_phone1
     *
     * @return the value of social_security.unit_phone1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getUnitPhone1() {
        return unitPhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.unit_phone1
     *
     * @param unitPhone1 the value for social_security.unit_phone1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setUnitPhone1(String unitPhone1) {
        this.unitPhone1 = unitPhone1 == null ? null : unitPhone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.unit_address
     *
     * @return the value of social_security.unit_address
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getUnitAddress() {
        return unitAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.unit_address
     *
     * @param unitAddress the value for social_security.unit_address
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setUnitAddress(String unitAddress) {
        this.unitAddress = unitAddress == null ? null : unitAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.unit_phone2
     *
     * @return the value of social_security.unit_phone2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getUnitPhone2() {
        return unitPhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.unit_phone2
     *
     * @param unitPhone2 the value for social_security.unit_phone2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setUnitPhone2(String unitPhone2) {
        this.unitPhone2 = unitPhone2 == null ? null : unitPhone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.linkman
     *
     * @return the value of social_security.linkman
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.linkman
     *
     * @param linkman the value for social_security.linkman
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.phone
     *
     * @return the value of social_security.phone
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.phone
     *
     * @param phone the value for social_security.phone
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.last_renew_date
     *
     * @return the value of social_security.last_renew_date
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public Date getLastRenewDate() {
        return lastRenewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.last_renew_date
     *
     * @param lastRenewDate the value for social_security.last_renew_date
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setLastRenewDate(Date lastRenewDate) {
        this.lastRenewDate = lastRenewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.create_time
     *
     * @return the value of social_security.create_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.create_time
     *
     * @param createTime the value for social_security.create_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.create_emp_id
     *
     * @return the value of social_security.create_emp_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.create_emp_id
     *
     * @param createEmpId the value for social_security.create_emp_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.status
     *
     * @return the value of social_security.status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.status
     *
     * @param status the value for social_security.status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security.remark
     *
     * @return the value of social_security.remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security.remark
     *
     * @param remark the value for social_security.remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}