package com.atguigu.bean;

public class SysLogWithBLOBs extends SysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.exception_info
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String exceptionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.params
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String params;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.exception_info
     *
     * @return the value of sys_log.exception_info
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getExceptionInfo() {
        return exceptionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.exception_info
     *
     * @param exceptionInfo the value for sys_log.exception_info
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setExceptionInfo(String exceptionInfo) {
        this.exceptionInfo = exceptionInfo == null ? null : exceptionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.params
     *
     * @return the value of sys_log.params
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.params
     *
     * @param params the value for sys_log.params
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }
}