package com.atguigu.bean;

import java.util.Date;

public class Telecom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.case_apply_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String caseApplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.mobile
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.operator
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.mobile_status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private Integer mobileStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.wide_band
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String wideBand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.network_provide
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String networkProvide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.wide_status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private Integer wideStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.cr_address
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String crAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.address
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.relation_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String relation1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.linkman_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String linkman1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.case_num_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String caseNum1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.relation_2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String relation2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.linkman_2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String linkman2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.case_num_2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String caseNum2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.create_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.create_emp_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telecom.remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.id
     *
     * @return the value of telecom.id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.id
     *
     * @param id the value for telecom.id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.case_apply_id
     *
     * @return the value of telecom.case_apply_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCaseApplyId() {
        return caseApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.case_apply_id
     *
     * @param caseApplyId the value for telecom.case_apply_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCaseApplyId(String caseApplyId) {
        this.caseApplyId = caseApplyId == null ? null : caseApplyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.mobile
     *
     * @return the value of telecom.mobile
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.mobile
     *
     * @param mobile the value for telecom.mobile
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.operator
     *
     * @return the value of telecom.operator
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.operator
     *
     * @param operator the value for telecom.operator
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.mobile_status
     *
     * @return the value of telecom.mobile_status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public Integer getMobileStatus() {
        return mobileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.mobile_status
     *
     * @param mobileStatus the value for telecom.mobile_status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setMobileStatus(Integer mobileStatus) {
        this.mobileStatus = mobileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.wide_band
     *
     * @return the value of telecom.wide_band
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getWideBand() {
        return wideBand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.wide_band
     *
     * @param wideBand the value for telecom.wide_band
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setWideBand(String wideBand) {
        this.wideBand = wideBand == null ? null : wideBand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.network_provide
     *
     * @return the value of telecom.network_provide
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getNetworkProvide() {
        return networkProvide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.network_provide
     *
     * @param networkProvide the value for telecom.network_provide
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setNetworkProvide(String networkProvide) {
        this.networkProvide = networkProvide == null ? null : networkProvide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.wide_status
     *
     * @return the value of telecom.wide_status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public Integer getWideStatus() {
        return wideStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.wide_status
     *
     * @param wideStatus the value for telecom.wide_status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setWideStatus(Integer wideStatus) {
        this.wideStatus = wideStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.cr_address
     *
     * @return the value of telecom.cr_address
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCrAddress() {
        return crAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.cr_address
     *
     * @param crAddress the value for telecom.cr_address
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCrAddress(String crAddress) {
        this.crAddress = crAddress == null ? null : crAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.address
     *
     * @return the value of telecom.address
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.address
     *
     * @param address the value for telecom.address
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.relation_1
     *
     * @return the value of telecom.relation_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getRelation1() {
        return relation1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.relation_1
     *
     * @param relation1 the value for telecom.relation_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setRelation1(String relation1) {
        this.relation1 = relation1 == null ? null : relation1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.linkman_1
     *
     * @return the value of telecom.linkman_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getLinkman1() {
        return linkman1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.linkman_1
     *
     * @param linkman1 the value for telecom.linkman_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setLinkman1(String linkman1) {
        this.linkman1 = linkman1 == null ? null : linkman1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.case_num_1
     *
     * @return the value of telecom.case_num_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCaseNum1() {
        return caseNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.case_num_1
     *
     * @param caseNum1 the value for telecom.case_num_1
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCaseNum1(String caseNum1) {
        this.caseNum1 = caseNum1 == null ? null : caseNum1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.relation_2
     *
     * @return the value of telecom.relation_2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getRelation2() {
        return relation2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.relation_2
     *
     * @param relation2 the value for telecom.relation_2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setRelation2(String relation2) {
        this.relation2 = relation2 == null ? null : relation2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.linkman_2
     *
     * @return the value of telecom.linkman_2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getLinkman2() {
        return linkman2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.linkman_2
     *
     * @param linkman2 the value for telecom.linkman_2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setLinkman2(String linkman2) {
        this.linkman2 = linkman2 == null ? null : linkman2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.case_num_2
     *
     * @return the value of telecom.case_num_2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCaseNum2() {
        return caseNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.case_num_2
     *
     * @param caseNum2 the value for telecom.case_num_2
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCaseNum2(String caseNum2) {
        this.caseNum2 = caseNum2 == null ? null : caseNum2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.create_time
     *
     * @return the value of telecom.create_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.create_time
     *
     * @param createTime the value for telecom.create_time
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.create_emp_id
     *
     * @return the value of telecom.create_emp_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.create_emp_id
     *
     * @param createEmpId the value for telecom.create_emp_id
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.status
     *
     * @return the value of telecom.status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.status
     *
     * @param status the value for telecom.status
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telecom.remark
     *
     * @return the value of telecom.remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telecom.remark
     *
     * @param remark the value for telecom.remark
     *
     * @mbggenerated Sat Apr 21 11:25:08 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}