package com.atguigu.mapper;

import com.atguigu.bean.AreaCopy;

public interface AreaCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(AreaCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(AreaCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    AreaCopy selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(AreaCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(AreaCopy record);
}