package com.atguigu.mapper;

import com.atguigu.bean.CallRecordIn;

public interface CallRecordInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_in
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_in
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(CallRecordIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_in
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(CallRecordIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_in
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    CallRecordIn selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_in
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(CallRecordIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_in
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CallRecordIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record_in
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(CallRecordIn record);
}