package com.atguigu.mapper;

import com.atguigu.bean.CaseBatchCopy;
import com.atguigu.bean.CaseBatchCopyWithBLOBs;

public interface CaseBatchCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(CaseBatchCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(CaseBatchCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    CaseBatchCopyWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(CaseBatchCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CaseBatchCopyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_batch_copy
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(CaseBatchCopy record);
}