package com.atguigu.mapper;

import com.atguigu.bean.CccWithBLOBs;

public interface CccMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccc
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(CccWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccc
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(CccWithBLOBs record);
}