package com.atguigu.mapper;

import com.atguigu.bean.CusArea;

public interface CusAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_area
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(Long areId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_area
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(CusArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_area
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(CusArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_area
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    CusArea selectByPrimaryKey(Long areId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_area
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(CusArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_area
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(CusArea record);
}