package com.atguigu.mapper;

import com.atguigu.bean.Entrust;
import com.atguigu.bean.EntrustWithBLOBs;

public interface EntrustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(EntrustWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(EntrustWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    EntrustWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(EntrustWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(EntrustWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(Entrust record);
}