package com.atguigu.mapper;

import com.atguigu.bean.EntrustCaseSource;

public interface EntrustCaseSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_case_source
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_case_source
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(EntrustCaseSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_case_source
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(EntrustCaseSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_case_source
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    EntrustCaseSource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_case_source
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(EntrustCaseSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_case_source
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(EntrustCaseSource record);
}