package com.atguigu.mapper;

import com.atguigu.bean.EntrustVisit;
import com.atguigu.bean.EntrustVisitWithBLOBs;

public interface EntrustVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_visit
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_visit
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(EntrustVisitWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_visit
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(EntrustVisitWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_visit
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    EntrustVisitWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_visit
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(EntrustVisitWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_visit
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(EntrustVisitWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_visit
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(EntrustVisit record);
}