package com.atguigu.mapper;

import com.atguigu.bean.Holiday;

public interface HolidayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    Holiday selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(Holiday record);
}