package com.atguigu.mapper;

import com.atguigu.bean.MessageReminder;

public interface MessageReminderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(MessageReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(MessageReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    MessageReminder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(MessageReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reminder
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(MessageReminder record);
}