package com.atguigu.mapper;

import com.atguigu.bean.SysColumn;

public interface SysColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(SysColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(SysColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    SysColumn selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(SysColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_column
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(SysColumn record);
}