package com.atguigu.mapper;

import com.atguigu.bean.SysPosition;

public interface SysPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(SysPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(SysPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    SysPosition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(SysPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(SysPosition record);
}