package com.atguigu.mapper;

import com.atguigu.bean.SysTimerTask;

public interface SysTimerTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timer_task
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timer_task
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insert(SysTimerTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timer_task
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int insertSelective(SysTimerTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timer_task
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    SysTimerTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timer_task
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKeySelective(SysTimerTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_timer_task
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    int updateByPrimaryKey(SysTimerTask record);
}