package com.atguigu.bean;

public class CccWithBLOBs extends Ccc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccc.remark
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccc.batch_log
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    private String batchLog;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccc.remark
     *
     * @return the value of ccc.remark
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccc.remark
     *
     * @param remark the value for ccc.remark
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccc.batch_log
     *
     * @return the value of ccc.batch_log
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public String getBatchLog() {
        return batchLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccc.batch_log
     *
     * @param batchLog the value for ccc.batch_log
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public void setBatchLog(String batchLog) {
        this.batchLog = batchLog == null ? null : batchLog.trim();
    }
}