package com.atguigu.bean;

public class SalEmpWithBLOBs extends SalEmp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_address
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    private String seAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_remark
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    private String seRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_pic
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    private String sePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_log
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    private String seLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_edc_bac
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    private String seEdcBac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_work_ex
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    private String seWorkEx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_transfer
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    private String seTransfer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_address
     *
     * @return the value of sal_emp.se_address
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public String getSeAddress() {
        return seAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_address
     *
     * @param seAddress the value for sal_emp.se_address
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public void setSeAddress(String seAddress) {
        this.seAddress = seAddress == null ? null : seAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_remark
     *
     * @return the value of sal_emp.se_remark
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public String getSeRemark() {
        return seRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_remark
     *
     * @param seRemark the value for sal_emp.se_remark
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public void setSeRemark(String seRemark) {
        this.seRemark = seRemark == null ? null : seRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_pic
     *
     * @return the value of sal_emp.se_pic
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public String getSePic() {
        return sePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_pic
     *
     * @param sePic the value for sal_emp.se_pic
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public void setSePic(String sePic) {
        this.sePic = sePic == null ? null : sePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_log
     *
     * @return the value of sal_emp.se_log
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public String getSeLog() {
        return seLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_log
     *
     * @param seLog the value for sal_emp.se_log
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public void setSeLog(String seLog) {
        this.seLog = seLog == null ? null : seLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_edc_bac
     *
     * @return the value of sal_emp.se_edc_bac
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public String getSeEdcBac() {
        return seEdcBac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_edc_bac
     *
     * @param seEdcBac the value for sal_emp.se_edc_bac
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public void setSeEdcBac(String seEdcBac) {
        this.seEdcBac = seEdcBac == null ? null : seEdcBac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_work_ex
     *
     * @return the value of sal_emp.se_work_ex
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public String getSeWorkEx() {
        return seWorkEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_work_ex
     *
     * @param seWorkEx the value for sal_emp.se_work_ex
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public void setSeWorkEx(String seWorkEx) {
        this.seWorkEx = seWorkEx == null ? null : seWorkEx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_transfer
     *
     * @return the value of sal_emp.se_transfer
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public String getSeTransfer() {
        return seTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_transfer
     *
     * @param seTransfer the value for sal_emp.se_transfer
     *
     * @mbggenerated Sat Apr 21 08:53:52 CST 2018
     */
    public void setSeTransfer(String seTransfer) {
        this.seTransfer = seTransfer == null ? null : seTransfer.trim();
    }
}